# Default values for cross-support-job
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: onedata/rest-cli:3.0.0-rc16
imagePullPolicy: IfNotPresent

wait_for:
  image: groundnuty/k8s-wait-for:0.3
  imagePullPolicy: IfNotPresent

# You can enable automatic deployment od the environment
# that this chart initializes
onedata-1p:
  enabled: true

# Or manually specify a helm release name of the already
# deployed environment
# releaseName: dev

oneprovider:
  - oneprovider-krakow

spaces:
  - name: "krk-c"
    supports:
      - provider: "krakow"
        storage_name: "ceph"
        size: '1000000000'
  - name: "krk-n"
    supports:
      - provider: "krakow"
        storage_name: "nfs"
        size: '1000000000'
  - name: "krk-3"
    supports:
      - provider: "krakow"
        storage_name: "s3"
        size: '1000000000'
  - name: "krk-g"
    supports:
      - provider: "krakow"
        storage_name: "gluster"
        size: '1000000000'