#!/usr/bin/env bash

FILENAME='templates/_hosts.tpl'

echo "{{/* This file is auto generated by gen_hosts.sh */}}" > $FILENAME

services=('volume-s3' 'volume-nfs' 'volume-ceph' 'oneprovider' 'onezone')
wait_fors=('volume-s3-init' 'volume-nfs' 'volume-ceph' 'oneprovider' 'onezone')

for (( i=0; i<=${#services[*]}; i++ )) ; do
service=${services[$i]}
wait_for=${wait_fors[$i]}
cat <<EOF>> $FILENAME

{{- define "${service}_wait_for" -}}
{{- \$suffix := default "" .Values.suffix -}}
{{- printf "%s-%s-%s" .Release.Name "${wait_for}" \$suffix | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- define "${service}_name" -}}
{{- \$suffix := default "" .Values.suffix -}}
{{- printf "%s-%s-%s" .Release.Name "${service}" \$suffix | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- define "${service}_service_url" -}}{{template "${service}_name" . }}.{{template "service_domain" . }}{{- end -}}
EOF

done
