{{/* This file is auto generated by gen_hosts.sh */}}

{{- define "volume-s3_wait_for" -}}
{{- $suffix := default "" .Values.suffix -}}
{{- printf "%s-%s-%s" .Release.Name "volume-s3-init" $suffix | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- define "volume-s3_name" -}}
{{- $suffix := default "" .Values.suffix -}}
{{- printf "%s-%s-%s" .Release.Name "volume-s3" $suffix | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- define "volume-s3_service_url" -}}{{template "volume-s3_name" . }}.{{template "service_domain" . }}{{- end -}}

{{- define "volume-nfs_wait_for" -}}
{{- $suffix := default "" .Values.suffix -}}
{{- printf "%s-%s-%s" .Release.Name "volume-nfs" $suffix | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- define "volume-nfs_name" -}}
{{- $suffix := default "" .Values.suffix -}}
{{- printf "%s-%s-%s" .Release.Name "volume-nfs" $suffix | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- define "volume-nfs_service_url" -}}{{template "volume-nfs_name" . }}.{{template "service_domain" . }}{{- end -}}

{{- define "volume-ceph_wait_for" -}}
{{- $suffix := default "" .Values.suffix -}}
{{- printf "%s-%s-%s" .Release.Name "volume-ceph" $suffix | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- define "volume-ceph_name" -}}
{{- $suffix := default "" .Values.suffix -}}
{{- printf "%s-%s-%s" .Release.Name "volume-ceph" $suffix | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- define "volume-ceph_service_url" -}}{{template "volume-ceph_name" . }}.{{template "service_domain" . }}{{- end -}}

{{- define "oneprovider_wait_for" -}}
{{- $suffix := default "" .Values.suffix -}}
{{- printf "%s-%s-%s" .Release.Name "oneprovider" $suffix | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- define "oneprovider_name" -}}
{{- $suffix := default "" .Values.suffix -}}
{{- printf "%s-%s-%s" .Release.Name "oneprovider" $suffix | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- define "oneprovider_service_url" -}}{{template "oneprovider_name" . }}.{{template "service_domain" . }}{{- end -}}

{{- define "onezone_wait_for" -}}
{{- $suffix := default "" .Values.suffix -}}
{{- printf "%s-%s-%s" .Release.Name "onezone" $suffix | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- define "onezone_name" -}}
{{- $suffix := default "" .Values.suffix -}}
{{- printf "%s-%s-%s" .Release.Name "onezone" $suffix | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- define "onezone_service_url" -}}{{template "onezone_name" . }}.{{template "service_domain" . }}{{- end -}}

{{- define "_wait_for" -}}
{{- $suffix := default "" .Values.suffix -}}
{{- printf "%s-%s-%s" .Release.Name "" $suffix | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- define "_name" -}}
{{- $suffix := default "" .Values.suffix -}}
{{- printf "%s-%s-%s" .Release.Name "" $suffix | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- define "_service_url" -}}{{template "_name" . }}.{{template "service_domain" . }}{{- end -}}
