name: volume-s3
version: 0.2.0
description: S3 Scality object storage service, suitable for testing purposes.
keywords:
  - onedata
  - volume-s3
  - storage
maintainers:
  - name: Michal Orzechowski
    email: orzechowski.michal@gmail.com
engine: gotpl